language: node_js
os: windows
node_js:
  - "stable"
install:
  - npm install -g istanbul
  - npm install -g codecov
  - npm install
script:
  - istanbul cover _mocha ./test/**/*.spec.js --report lcovonly -- -R spec
  - codecov
