language: node_js
node_js:
  - "stable"
install:
  - npm i
  - npm i -g coveralls
  - npm i -g istanbul
script:
  - mocha ./test/**/*.spec.js --exit
  - istanbul cover ./node_modules/mocha/bin/_mocha ./test/**/*.spec.js --exit
  - cat ./coverage/lcov.info | coveralls
notifications:
  email: false
